# Exercise 3 - stack the country statistics

In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("Afghanistan.csv")
df2 = pd.read_csv("Albania.csv")
df3 = pd.read_csv("Algeria.csv")
df4 = pd.read_csv("Angola.csv")
df5 = pd.read_csv("Armenia.csv")

In [4]:
# --------------------------------------------------------------
# A. Use pandas.concat to combine 4 countries from the Maddisson CSV files in one df.
# --------------------------------------------------------------

df = pd.concat([df1,df2,df3,df4])
df

         Entity Code  Year           GDP  GDP (Annotations)
0   Afghanistan  AFG  1950    9421400000                NaN
1   Afghanistan  AFG  1951    9692280000                NaN
2   Afghanistan  AFG  1952   10017325000                NaN
3   Afghanistan  AFG  1953   10630520000                NaN
4   Afghanistan  AFG  1954   10866360000                NaN
..          ...  ...   ...           ...                ...
68       Angola  AGO  2018  162550037080                NaN
69       Angola  AGO  2019  161408924528                NaN
70       Angola  AGO  2020  152308692850                NaN
71       Angola  AGO  2021  153971902307                NaN
72       Angola  AGO  2022  158346237030                NaN

[301 rows x 5 columns]

In [5]:
# --------------------------------------------------------------
# B. Find statistical data for four different countries and use `pandas.concat()` to combine the results into a single DataFrame.
# --------------------------------------------------------------
def statdata(dfname,country):
    minyear = dfname["Year"].min()
    maxyear = dfname['Year'].max()
    gdpminyear = round(dfname.loc[dfname["Year"].idxmin(),'GDP']/1e9, 2)
    gdpmaxyear = round(dfname.loc[dfname["Year"].idxmax(),'GDP']/1e9, 2)
    avegdp = round(dfname['GDP'].mean()/1e9,2)
    n = maxyear - minyear
    cagr = round(((gdpmaxyear/gdpminyear)**(1/n) - 1)*100, 2)
    data = {'Country': [country],
        'Min Year': [minyear],
        'Max Year': [maxyear],
        'GDP Min Year': [gdpminyear],
        'GDP Max Year': [gdpmaxyear],
        'Avg GDP': [avegdp],
        'CAGR (%)': [cagr]}
    
    return pd.DataFrame(data)

statdata(df1,'Afghanistan')
finaldf = pd.concat([statdata(df1,'Afghanistan'),statdata(df2,'Albania'),statdata(df3,'Algeria'),statdata(df4,'Angola')])
finaldf

,Country,Min Year,Max Year,GDP Min Year,GDP Max Year,Avg GDP,CAGR (%)
0,Afghanistan,1950,2022,9.42,53.30,23.70,2.44
0,Albania,1870,2022,0.43,36.17,12.55,2.96
0,Algeria,1820,2022,1.84,595.82,184.65,2.90
0,Angola,1950,2022,6.91,158.35,43.77,4.45