# Exercise 2 - value_counts inside a group
Use the survey from Exercise 1. First run `value_counts(normalize=True)` on Favorite Pet.

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("2026-DEAI-intro-data-engineering-people-preferences-dataset.csv",sep=";")
df.head()

,Name_Pseudoname,Original Color Group,Your favorite color,Dream Holiday Destination,Favorite Pet,Favorite Season,Music,Favorite Food
0,David,Light Blue,black,Hawaii,Dog,Summer,Rap,Pizza
1,Laura,Purple,black,Hawaii,Cat,Summer,Rock,Sushi
2,Markku,Green,Blue,SanTorini,Dog,Summer,Pop,Sushi
3,Jani,Red,black,Moon,Dog,Winter,Rock,Pizza
4,Daniel,Blue,Green,Hawaii,Dog,Winter,Rock,Sushi

### A) Keep only the rows where Favorite Pet is dog. Run `value_counts(normalize=True)` on Dream Holiday Destination. Which category changes most which least?

In [13]:
dog = df[df['Favorite Pet']=='Dog']
dog.head(3)
# just to check Type and DataType:
print("** Type of food variable:",type(dog))
print("** Data type of DataFrame:\n",dog.dtypes)
print("** DataFrame info:\n",dog.info())

** Type of food variable: <class 'pandas.DataFrame'>
** Data type of DataFrame:
 Name_Pseudoname              str
Original Color Group         str
Your favorite color          str
Dream Holiday Destination    str
Favorite Pet                 str
Favorite Season              str
Music                        str
Favorite Food                str
dtype: object
<class 'pandas.DataFrame'>
Index: 26 entries, 0 to 44
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Name_Pseudoname            26 non-null     str
 1   Original Color Group       26 non-null     str
 2   Your favorite color        26 non-null     str
 3   Dream Holiday Destination  26 non-null     str
 4   Favorite Pet               26 non-null     str
 5   Favorite Season            26 non-null     str
 6   Music                      26 non-null     str
 7   Favorite Food              26 non-null     str
dtypes: str(8)
memory usage: 1.8 KB
** DataFrame info:
 None

In [14]:
holiday = dog.value_counts('Dream Holiday Destination', normalize=True)
print(holiday)

choice = []
for i in range(len(holiday)):
    value = round(holiday.iloc[i]*100,2)
    choice.append(value)
    print(f'- Share of {holiday.index[i]}: {choice[i]}%')

maxchoice = holiday.idxmax()
maxnumber = round(holiday[maxchoice]*100,2)
print(f'- Most common choice: {maxchoice} = {maxnumber}%')

# just to check Type and DataType:
print("** Type of music variable:",type(holiday))
print("** Data type of DataFrame/Series:",holiday.dtype)

Dream Holiday Destination
Hawaii       0.384615
Paris        0.346154
Moon         0.153846
SanTorini    0.115385
Name: proportion, dtype: float64
- Share of Hawaii: 38.46%
- Share of Paris: 34.62%
- Share of Moon: 15.38%
- Share of SanTorini: 11.54%
- Most common choice: Hawaii = 38.46%
** Type of music variable: <class 'pandas.Series'>
** Data type of DataFrame/Series: float64

### B) Do the same analysis for Favorite Pet equal to cat. Which destination shows up for cats and did not show up for dogs?

In [15]:
cat = df[df['Favorite Pet']=='Cat']
cat.head(3)

,Name_Pseudoname,Original Color Group,Your favorite color,Dream Holiday Destination,Favorite Pet,Favorite Season,Music,Favorite Food
1,Laura,Purple,black,Hawaii,Cat,Summer,Rock,Sushi
6,Mehak,Orange,Green,Moon,Cat,Fall,Classical,Pizza
7,Sarker,Orange,Blue,Paris,Cat,Fall,Classical,Kebab

In [16]:
holidaycat = cat.value_counts('Dream Holiday Destination', normalize=True)
print(holidaycat)

choicecat = []
for i in range(len(holidaycat)):
    value = round(holidaycat.iloc[i]*100,2)
    choicecat.append(value)
    print(f'- Share of {holidaycat.index[i]}: {choicecat[i]}%')

maxchoice = holidaycat.idxmax()
maxnumber = round(holidaycat[maxchoice]*100,2)
print(f'- Most common choice: {maxchoice} = {maxnumber}%')

# just to check Type and DataType:
print("** Type of music variable:",type(holidaycat))
print("** Data type of DataFrame/Series:",holidaycat.dtype)

Dream Holiday Destination
Hawaii       0.368421
Moon         0.210526
Turku        0.210526
Paris        0.157895
SanTorini    0.052632
Name: proportion, dtype: float64
- Share of Hawaii: 36.84%
- Share of Moon: 21.05%
- Share of Turku: 21.05%
- Share of Paris: 15.79%
- Share of SanTorini: 5.26%
- Most common choice: Hawaii = 36.84%
** Type of music variable: <class 'pandas.Series'>
** Data type of DataFrame/Series: float64

In [17]:
print('- Holiday for Cat:\n',holidaycat)
print('- Holiday for Dog:\n',holiday)

set_cat = set()
for i in range(len(holidaycat)):
    set_cat.add(holidaycat.index[i])

set_dog = set()
for i in range(len(holiday)):
    set_dog.add(holiday.index[i])

catdes = list(set_cat - set_dog)
print('- Destinations show up only in Cat:', catdes)

- Holiday for Cat:
 Dream Holiday Destination
Hawaii       0.368421
Moon         0.210526
Turku        0.210526
Paris        0.157895
SanTorini    0.052632
Name: proportion, dtype: float64
- Holiday for Dog:
 Dream Holiday Destination
Hawaii       0.384615
Paris        0.346154
Moon         0.153846
SanTorini    0.115385
Name: proportion, dtype: float64
- Destinations show up only in Cat: ['Turku']

### C) Keep only the rows where Favorite Season is summer, and run `value_counts(normalize=True)` on Favorite Pet. Then do the same for winter. In both seasons, which pet is the most common?

In [ ]:
# Favorite Season = Summer:
summer = df.loc[df['Favorite Season'] == 'Summer']
summer = df[df['Favorite Season'] == 'Summer']
summer.head()

,Name_Pseudoname,Original Color Group,Your favorite color,Dream Holiday Destination,Favorite Pet,Favorite Season,Music,Favorite Food
0,David,Light Blue,black,Hawaii,Dog,Summer,Rap,Pizza
1,Laura,Purple,black,Hawaii,Cat,Summer,Rock,Sushi
2,Markku,Green,Blue,SanTorini,Dog,Summer,Pop,Sushi
5,HerkkuSieni,Green,Blue,Hawaii,Dog,Summer,Rap,Pizza
8,ste,Purple,Green,Moon,Cat,Summer,Pop,Pizza

In [23]:
winter = df.loc[df['Favorite Season']=='Winter']
winter = df[df['Favorite Season']=='Winter']
winter.head()

,Name_Pseudoname,Original Color Group,Your favorite color,Dream Holiday Destination,Favorite Pet,Favorite Season,Music,Favorite Food
3,Jani,Red,black,Moon,Dog,Winter,Rock,Pizza
4,Daniel,Blue,Green,Hawaii,Dog,Winter,Rock,Sushi
9,Markus,Purple,red,Hawaii,Dog,Winter,Pop,Kebab
19,D,Light Blue,Blue,Hawaii,Cat,Winter,Rock,Kebab
33,Tommi,White,black,Hawaii,Dog,Winter,Pop,Sushi

In [102]:
petsummer = summer.value_counts('Favorite Pet',normalize=True)
petsummer.name = 'Summer'
print('A) Favorite pet for favorite summer:\n',petsummer)
petwinter = winter.value_counts('Favorite Pet',normalize=True)
petwinter.name = 'Winter'
print('B) Favorite pet for favorite winter:\n',petwinter)

# just to check Type and DataType:
print("** Type of food variable:",type(petsummer))
print("** Data type of DataFrame/Series:",petsummer.dtype)

A) Favorite pet for favorite summer:
 Favorite Pet
Dog        0.615385
Cat        0.346154
Hamster    0.038462
Name: Summer, dtype: float64
B) Favorite pet for favorite winter:
 Favorite Pet
Dog    0.7
Cat    0.3
Name: Winter, dtype: float64
** Type of food variable: <class 'pandas.Series'>
** Data type of DataFrame/Series: float64

In [103]:
# Which pet is the most common?
## FAVORITE SUMMER:
def checkcommon(petseason):
    maxpercent = round(petseason.max()*100,2)
    mostcommon = petseason.index[petseason == maxpercent]
    mostcommon = petseason.idxmax()
    print(f'- Most common pet for favorite {petseason.name}: {mostcommon} = {maxpercent}%')

checkcommon(petsummer)

## FAVORITE WINTER:
checkcommon(petwinter)

## COMPARING SUMMBER & WINTER:
def common_for_both():
    for i in range(len(petsummer)):
        for j in range(len(petwinter)):
            if petsummer.index[i] == petwinter.index[j]:
                return print('--> Most common pet for both Summer and Winter: ',petsummer.index[i])
    return print('--> There is no common pet between Summer and Winter!')

common_for_both()

- Most common pet for favorite Summer: Dog = 61.54%
- Most common pet for favorite Winter: Dog = 70.0%
--> Most common pet for both Summer and Winter:  Dog