# Small Jupyter Notebook Demo

In [15]:
# Just checking, that the environment works
print("hello")

hello

Please try out these commands (preferably create a new Jupyter Notebook and type the commands yourself instead of using copy-pasting).

You can run code cells using the run-button above, or test e.g. Ctrl-Enter and Shift-Enter. Google for more handy keyboard shortcuts used in Jupyter Notebook.

In [16]:
# This is how you import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [17]:
# Load dataset, let's use the Iris dataset: https://www.kaggle.com/datasets/uciml/iris.
# Data is loaded to variable iris.
iris = sns.load_dataset("iris")

In [18]:
# Show first few rows of the dataset
# head() shows 5 first lines, but head(10) shows 10 first lines

iris.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [19]:
# tail() shows five last lines of the dataset
iris.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [20]:
# This command shows the number of rows and columns. You get the same info by using the info(), see below.
iris.shape

(150, 5)

In [21]:
# This is a very usefull command. Learn it!
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [22]:
# Mean, mode, median etc. can be calculated for each variable (column)...
np.mean(iris["sepal_length"])

np.float64(5.843333333333334)

In [23]:
# ... but learn also this describe()-function, because it does all the measures for every column.
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

The end! Notice, that this is not a code cell, but a Markdown cell. But you can use Shift-Enter or Ctrl-Enter also in Markdown cells, when you are finished typing.

You can modify this text by double clicking here.